//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_TOdrinkGO.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Usuario()
        {
            this.Venta = new HashSet<Venta>();
        }
    
        public int id_usuario { get; set; }
        public string nombre { get; set; }
        public string clave { get; set; }
        public Nullable<int> id_roles { get; set; }
        public Nullable<int> estado { get; set; }
        public string peril { get; set; }
        public Nullable<int> local { get; set; }
    
        public virtual EstadoUs EstadoUs { get; set; }
        public virtual Local Local1 { get; set; }
        public virtual Perfil Perfil { get; set; }
        public virtual Roles Roles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Venta> Venta { get; set; }
    }
}
